import 'book.dart';

List<Book> bookshelf = [
  Book(
    kadi: "Nutuk",
    kyazar: "Mustafa Kemal Atatürk",
    kfoto: "assets/images/nutuk.jpg",
    kbegen: false,
    aciklama:"Nutuk, yazıldığı dönemde Cumhur Reisi ve Cumhuriyet Halk Fırkası Umumi Reisi olan Gazi Mustafa Kemal'in 15-20 Ekim 1927 tarihlerinde, 1919'dan 1927'ye dek kendisinin ve silah arkadaşlarının faaliyetlerini özetlediği konuşmasının metnidir. ",
    kisim:"Kültür Bakanlığı Yayınevi tarafından belgeler bölümü dışında yaklaşık 900 sayfalık bir kitap olarak yayımlanmıştır ve Türkiye'nin bu dönemle ilgili en temel resmî tarih kaynağı olma niteliğindedir." ,
  ),
  Book(
    kadi: "Fareler ve İnsanlar",
    kyazar: "John Steinbeck",
    kfoto: "assets/images/fareler_ve_insanlar.jpg",
    kbegen: false,
    aciklama:"    Roman, dostluk, yalnızlık, insan doğası ve hayal kırıklığı gibi temaları ele almaktadır. Steinbeck'in akıcı ve sade anlatımı, karakterlerin duygularını başarıyla yansıtmaktadır. " ,
    kisim:"Fareler ve İnsanlar, Amerikan edebiyatının en önemli eserlerinden biri olarak kabul edilir.",
  ),
  Book(
    kadi: "Beyaz Zambaklar Ülkesinde",
    kyazar: "Grigoriy Petrov",
    kfoto: "assets/images/beyaz_zambaklar_ulkesinde.jpg",
    kbegen: false,
    aciklama:"Roman, Aitmatov'un hayatındaki kişisel deneyimleri yansıtır ve Kazakistan'ın güzel doğasını, kültürünü ve insanlarını anlatırken aynı zamanda Sovyet döneminin sert gerçeklerine de bir gönderme yapar. \n Ayrıca, insanların doğayla olan ilişkisini ve doğanın korunması gerekliliğini vurgular." ,
    kisim:"Kitapta, yoksul bir Kazak köyünden gelen genç bir adam olan Aitmatov, kendi doğal güzelliği ile ünlü Kazakistan steppe'sindeki yaşamına yeniden bağlanmaya çalışır. Ancak, ülkesinin Sovyetler Birliği tarafından yönetilmesi, hükümetin Kazakistan'ı kontrol etmek için uyguladığı politikalar ve köyündeki insanların yoksulluğu ve acımasızlığı, Aitmatov'un gerçek kimliği ve dünya görüşü ile çatışmalar yaratır.",
  ),
  Book(
    kadi: "Kızıl Veba",
    kyazar: "Jack London",
    kfoto: "assets/images/kizil_veba.jpg",
    kbegen: false,
    aciklama:"Öyküde, bir adamın arkadaşı olan Prens Prospero, salgından kaçınmak için zengin bir malikâyede kendini ve diğer zengin arkadaşlarını kapatır.\n Ancak bir gece, parti sırasında giydiği korkunç kostümle dolaşan bir figür, Prens'in dikkatini çeker ve olaylar kontrolden çıkar." ,
    kisim:"Kızıl Veba,korku edebiyatı alanında önemli bir eseri olarak kabul edilir ve okuyucuların karanlık, gotik atmosferi ve gerilim dolu hikayesiyle ilgisini çeker.",
  ),
  Book(
    kadi: "Altıncı Koğuş",
    kyazar: "Anton Pavloviç Çehov",
    kfoto: "assets/images/altinci_kogus.jpg",
    kbegen: false,
    aciklama:"Kitapta yer alan öykülerin çoğunda, sıradan insanların hayatlarına bir pencere açılır. Okuyucular, öykülerde yer alan karakterlerin sıradan hayatlarının içinde kaybolurken, yazarın kendine özgü üslubuyla yaratılan atmosferin içinde kendilerini bulurlar. " ,
    kisim:"Kitapta ayrıca, insanların hayatındaki küçük detayların anlamı ve önemi de vurgulanır.Altıncı Koğuş, Türk edebiyatında modern öykücülüğün önemli bir örneği olarak kabul edilir. Yazarın dil ve üslup kullanımı, sıradan insanların hayatlarına dokunan hikayeleri ve İstanbul'un farklı semtlerinin atmosferini başarıyla yansıtması nedeniyle Türk edebiyatında önemli bir yere sahiptir.",
  ),
  Book(
    kadi: "Kavgam",
    kyazar: "Adolf Hitler",
    kfoto: "assets/images/kavgam.png",
    kbegen: false,
    aciklama:"Kitap, Hitler'in kişisel hayatını, politik felsefesini ve hareketinin ideolojik temellerini anlatır. Hitler, kitapta Almanya'nın I. Dünya Savaşı'nda yenilgisini ve Versay Antlaşması'nın ülkenin acımasızca cezalandırılmasına yol açmasını eleştirir ve Almanya'nın uluslararası arenada güçlü bir rol oynaması için gerekenlerin neler olduğunu tartışır. " ,
    kisim:"Ayrıca kitapta, Hitlerin ırk teorileri, Yahudi karşıtı düşünceleri ve totaliter bir devlet yönetimine olan inancı da yer alır. Kavgam, Nazizmin yükselişinde önemli bir rol oynamış ve Hitlerin ideolojik görüşlerini anlamak için önemli bir kaynak olarak kabul edilmiştir. Ancak, kitapta yer alan fikirler çoğu insan tarafından tehlikeli ve aşırı olarak kabul edilmektedir.",
  ),
  Book(
    kadi: "Satranç",
    kyazar: "Stefan Zweig",
    kfoto: "assets/images/satranc.jpg",
    kbegen: false,
    aciklama:"Satranç, Avusturyalı yazar Stefan Zweig'in en ünlü eserlerinden biridir. Kitap, 1941 yılında yayınlanmıştır ve kısa bir roman formunda yazılmıştır.Roman, yakın zamanda serbest bırakılan bir mahkum olan ve satranç tutkusunu yeniden keşfeden Dr. B adlı bir karakterin hikayesini anlatır. Dr. B, satranç oynamaya başladığında, yaşadığı ülkede gerçekleşen tarihi bir olay olan bir satranç maçını yeniden yaşar. Bu maç, dünya satranç şampiyonu ve bir Nazi subayı olan Czentovic ile bir önceki şampiyon olan, ancak Nazi rejiminden kaçan bir Avusturyalı Yahudi olan Dr. B arasında gerçekleşir." ,
    kisim:"Kitap, Zweig'in dilinde sade ve akıcı bir şekilde yazılmıştır ve satranç oyununun insan zihnindeki gücüne, insan karakterlerinin çeşitliliğine ve insanın yaşamındaki mücadelelere dair derin düşüncelere yer verir. Satranç, Zweig'in yazarlık kariyerinin zirvesi olarak kabul edilir ve birçok okuyucu tarafından unutulmaz bir klasik olarak değerlendirilir.",
  ),
  Book(
    kadi: "Olağanüstü Bir Gece",
    kyazar: "Stefan Zweig",
    kfoto: "assets/images/olaganustu_bir_gece.jpg",
    kbegen: false,
    aciklama:" Stefan Zweig'in kısa bir öyküsüdür. Öykü, bir trende yolda olan bir kadın ve bir adamın arasında geçen olayları anlatır.Kadın, trende yanına oturan yabancı bir adamın sürekli kendisine bakmasından rahatsız olur ve bu durumun sonunda adamla konuşmaya karar verir. İkisi de kendi yaşamlarındaki hayal kırıklıkları ve yalnızlıkları paylaşırlar ve bu sohbet, beklenmedik bir şekilde olağanüstü bir geceye dönüşür.",
    kisim:"Zweig, öyküde insanların birbirleriyle olan bağlantılarının gücünü ve insanların hayatlarında küçük bir değişimin nasıl büyük bir etki yaratabileceğini anlatır. Olağanüstü Bir Gece, Zweig'in anlatımının gücüyle etkileyici bir şekilde yazılmış kısa bir eserdir ve insan doğasına dair önemli bir anlayış sunar." ,
  ),
  Book(
    kadi: "Vatan Yahut Silistre",
    kyazar: "Namık Kemal",
    kfoto: "assets/images/vatan_yahut_silistre.jpg",
    kbegen: false,
    aciklama:"Namık Kemal'in Osmanlı İmparatorluğu'nun çöküş döneminde geçen ve Balkanlardaki Osmanlı-Rus savaşı sırasında yaşanan olayları anlattığı tarihi bir romanıdır. Kitap, 1873 yılında yayınlanmıştır ve Türk edebiyatının ilk tarihî romanlarından biridir.Roman, Osmanlı askerleri ile Rus ordusu arasındaki çatışmaların yer aldığı Silistre Kalesi'nin kuşatmasını konu alır. Hikaye, iki kardeşin ve aşklarının bu savaşın ortasında nasıl bir trajediye dönüştüğünü anlatır. " ,
    kisim:"Ayrıca, Osmanlı ordusundaki disiplinsizlik, yönetim zaafı ve çürümüşlük gibi dönemin siyasi sorunlarına da değinilir.Vatan Yahut Silistre, Namık Kemal'in milliyetçi düşüncelerinin ve Osmanlı İmparatorluğu'nun yeniden yapılandırılması için duyduğu umudun bir yansımasıdır. Kitap, Osmanlı İmparatorluğu'nun çöküş dönemine dair tarihi bir anlayış sunar ve Türk edebiyatının tarihî roman türünde önemli bir eseridir.",
  ),
  Book(
    kadi: "Küçük Meşe Palamudu",
    kyazar: "Melanie Joyce",
    kfoto: "assets/images/mese_palamudu.jpg",
    kbegen: false,
    aciklama:" Küçük Meşe Palamudu çocuklar için yazılmış bir öykü kitabıdır. Kitap, hayal gücüne önem veren, paylaşımı ve arkadaşlığı vurgulayan bir hikaye anlatmaktadır. Ana karakterimiz küçük meşe palamudu, diğer arkadaşları olan kuş, sincap, fare ve tavşan ile birlikte büyük bir maceraya atılır. Bu macera sırasında birçok engel ile karşılaşırlar ancak dayanışma ve arkadaşlıkları sayesinde bu zorlukları aşarlar. " ,
    kisim:"Kitap, çocukların empati kurmasına, hayal güçlerini geliştirmesine, arkadaşlık ve paylaşım kavramlarını anlamalarına yardımcı olmak için yazılmıştır.",
  ),
];
